---
- name: "PLAY1: Capture and store vrf config"
  hosts: routers
  connection: network_cli
  tasks:
     - name: "TASK 1: Get VRF config from routers" 
       ios_command: 
          commands: "show running-config | section ^interface" 
       register: cli_result

     - name: "TASK 2: Print VRF output"
       debug:
          msg: "{{ cli_result.stdout[0]}}"
     - name: "TASK 3: Copy configs to file"
       copy:
          content: "{{ cli_result.stdout[0] }}"
          dest: "/etc/ansible/{{ inventory_hostname }}.txt"
